name: lumigen
description: "Record the Air Quality Index of The Room You're In"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4h

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_admin: ^0.2.0
  firebase_core: ^3.2.0
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  google_fonts: ^4.0.4
  intl: ^0.18.1
  fl_chart: ^0.68.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 23 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/transparent_logo.png
